### PR TITLE
[WIP] Openai plugins support

### PR DESCRIPTION
**Pull request by evahteev**
### Background

OpenAI declared their interface for plugins, which effectively could be commands for Auto-GPT OpenAI plugins spec https://platform.openai.com/docs/plugins/introduction .

The idea here is to add support for loading plugins created, for OpenAI like for testing purposes Weather plugin https://weathergpt.vercel.app/
https://weathergpt.vercel.app/.well-known/ai-plugin.json
https://github.com/steven-tey/weathergpt

### Changes

* reshaped plugins and added tests
* Added OpenAI plugins loader
* Added BaseOpenAIPlugin(AutoGPTPluginTemplate) class instance of every OpenAI plugin added

### Documentation

WIP

### Test Plan

Unit and integration tests

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes

### CODE REVIEW

**Comment by BillSchumacher** [comment]
I like where you're going with this but if we're going to add a test plugin let's make sure it tests the functionality.

You can see an example here: https://github.com/BillSchumacher/Auto-GPT-Vicuna

**Comment by evahteev** [comment]
> I like where you're going with this but if we're going to add a test plugin let's make sure it tests the functionality.
> 
> You can see an example here: https://github.com/BillSchumacher/Auto-GPT-Vicuna

Added test plugging generated from Auto-GPT-Vicuma plugin, working on it, thanks!

**Comment by BillSchumacher** [comment]
I'm going to go ahead and merge this as is, if you have more please submit another PR.

**Comment by BillSchumacher** [comment]
Otherwise you would have massive conflicts to deal with.

**Comment by BillSchumacher** [comment]
Thanks for your hard work!

**Pull request merged**
